apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: merch-manager-frontend
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-limit: "1"
        run.googleapis.com/memory-limit: "512Mi"
    spec:
      containerConcurrency: 100
      containers:
      - image: us-central1-docker.pkg.dev/neon-vigil-395120/merch-manager/merch-manager-frontend:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
